services:
  # --- Backend (Express) ---
  - type: web
    name: zealthy-backend
    env: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: "npm ci"
    startCommand: "node index.js"
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_URL
        value: "postgresql://neondb_owner:npg_KrtX59kMjaRO@ep-withered-wildflower-addb8fho-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: FRONTEND_URL           
        value: "https://zealthy-frontend-9alq.onrender.com"

  # --- Frontend (Vite) ---
  - type: web
    name: zealthy-frontend
    runtime: static       
    rootDir: frontend
    autoDeploy: true
    buildCommand: "npm ci && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL          
        value: "https://zealthy-backend-bkn4.onrender.com/api"