services:
  # --- Backend (Express) ---
  - type: web
    name: zealthy-backend
    env: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: "npm ci"
    startCommand: "node index.js"
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: psql 'postgresql://neondb_owner:npg_KrtX59kMjaRO@ep-withered-wildflower-addb8fho-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'          # <- put your Neon connection string here (with sslmode=require)
        value: "postgresql://<user>:<password>@<host>/<db>?sslmode=require"
      - key: FRONTEND_URL           
        value: "https://zealthy-frontend.onrender.com"

  # --- Frontend (Vite) ---
  - type: static
    name: zealthy-frontend         
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL          
        value: "https://zealthy-backend.onrender.com/api"